
const LEFT_SQUARE_BRACKET_UPPER_CORNER: &str =	"⎡";
const LEFT_SQUARE_BRACKET_EXTENSION: &str = "⎢";
const LEFT_SQUARE_BRACKET_LOWER_CORNER: &str = "⎣";
const RIGHT_SQUARE_BRACKET_UPPER_CORNER: &str = "⎤";
const RIGHT_SQUARE_BRACKET_EXTENSION: &str = "⎥";
const RIGHT_SQUARE_BRACKET_LOWER_CORNER: &str = "⎦";