
const _LEFT_SQUARE_BRACKET_UPPER_CORNER: &str =	"⎡";
const _LEFT_SQUARE_BRACKET_EXTENSION: &str = "⎢";
const _LEFT_SQUARE_BRACKET_LOWER_CORNER: &str = "⎣";
const _RIGHT_SQUARE_BRACKET_UPPER_CORNER: &str = "⎤";
const _RIGHT_SQUARE_BRACKET_EXTENSION: &str = "⎥";
const _RIGHT_SQUARE_BRACKET_LOWER_CORNER: &str = "⎦";